#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# When it receives SIGTERM, it displays "I am invincible!!!" and continues running

trap 'echo I am invincible!!!' TERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
